# Built with Jekyll 3.2.0

# Setup
title:               Dongmyeong Lee
tagline:             'AILEVER'
description:         'Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning. -Albert Einstein- '
url:                 'http://userdyk-github.github.io'
baseurl:             ''

# About/contact
author:
  name:              Dongmyeong Lee
  url:               https://userdyk-github.github.io
  email:             dongmyeong.6626070@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: red

# Permalinks
permalink: none

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor





# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #- jemoji               # 주석처리
  - jekyll-include-cache  # 추가

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #- jemoji                  # 주석처리
  - jekyll-include-cache  #추가
